In [3]:
message = "Hello Data Science"
message

'Hello Data Science'

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import random

In [5]:
list_1 = [1,2,3,4,5]
np_arr_1 = np.array(list_1, dtype = np.int8)
np_arr_1

m_list1_1 = [[1,2,3],[4,5,6], [7,8,9]]
np_m_arr_1 = np.array(m_list1_1)

np.arange(1,10)
np.linspace(0,5,5)
np.zeros(4)
np.ones((2,3))
np_arr_1.size
np_arr_2 = np.array([1,2,3,4,5,6])
np_arr_2.dtype

np.random.randint(10, 50, size = (2,3))

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

## Section 133

### Slicing and Indexes

In [6]:
# np_m_arr_1[0,0] = 2
# np_m_arr_1.itemset((0,1), 1)
# print("np_m_arr_1\n", np_m_arr_1)
# np_m_arr_1.shape
# np_m_arr_1[0,2]

# np.take(np_m_arr_1, [0,3,6])
# np.put(np_m_arr_1, [0,3,6], [10,10,10])
# np_m_arr_1
np_arr_1
# np_arr_1[:5:2]

np_m_arr_1[:,1]

np_m_arr_1[::-1]

evens = np_m_arr_1[np_m_arr_1 % 2 == 0]
evens

np_m_arr_1[np_m_arr_1 > 5]


np_m_arr_1[(np_m_arr_1 > 5) & (np_m_arr_1 < 9)]

np_m_arr_1[(np_m_arr_1 > 5) | (np_m_arr_1 == 10)]

np.unique(np_m_arr_1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

np_m_arr_1.itemset?

## Section 134

### Reshaping Arrays

In [7]:
np_m_arr_1.reshape((1,9))
np.resize(np_m_arr_1, (2,5))

np_m_arr_1.transpose()

np_m_arr_1.swapaxes(0,1)

np_m_arr_1.flatten('F')

np_m_arr_1.sort(axis=1)
np_m_arr_1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Stacking & Splitting

In [20]:
ss_arr_1 = np.random.randint(10, size=(2,2))
print("ss_arr_1\n", ss_arr_1)

ss_arr_2 = np.random.randint(10, size=(2,2))
print("ss_arr_2\n", ss_arr_2)

np.vstack((ss_arr_1, ss_arr_2))

np.hstack((ss_arr_1, ss_arr_2))


ss_arr_3 = np.delete(ss_arr_1,  1, 0)
ss_arr_4 = np.delete(ss_arr_2, 1, 0)

np.column_stack((ss_arr_3, ss_arr_4))

np.row_stack((ss_arr_3, ss_arr_4))

ss_arr_5 = np.random.randint(10, size= (2,10))
print("")

ss_arr_1
 [[3 9]
 [9 6]]
ss_arr_2
 [[5 9]
 [9 2]]


array([[3, 9],
       [5, 9]])

## Copying

In [24]:
cp_arr_1 = np.random.randint(10, size = (2,2))

cp_arr_2 = cp_arr_1

cp_arr_1[0,0] = 2

print("cp_arr_1\n", cp_arr_1)
print("cp_arr_2\n", cp_arr_2)

cp_arr_3 = cp_arr_1.view()
cp_arr_3.flatten("F")
print("cp_arr_1\n", cp_arr_1)

cp_arr_4 = cp_arr_1.copy()

cp_arr_1
 [[2 0]
 [1 5]]
cp_arr_2
 [[2 0]
 [1 5]]
cp_arr_1
 [[2 0]
 [1 5]]


## Section 135

## Basic Math

In [4]:
arr_3 = np.array([1,2,3,4])
arr_4 = np.array([1,4,6,8])

In [6]:
arr_3 + arr_4

array([ 2,  6,  9, 12])

In [8]:
arr_6 = random.randint(100, size = (2,3))

arr_5 = random.randint(100, size = (4))

In [10]:
random.rand(4)
random.choice(arr_3)

2

In [17]:
print(arr_6)
arr_6.sum(axis=0)
# arr_6.cumsum(axis=1)

[[71 53 85]
 [86 99 78]]


array([157, 152, 163])

## Reading from Files


In [ ]:
import pandas as pd
from numpy import genfromtxt

ic_sales = pd.read_csv("icrecreamsales.csv").to_numpy()

ic_sales_2 = genfromtxt('icreacmsales.csv', delimiter = ',')
ic_sales_2 = [row[~np.isnan(row)] for row in ic_sales_2]
ic_sales_2